// Arabic dictionary lifted verbatim from the design source (i18n.js).
// Keys are the English strings exactly as they appear in the UI; a string
// with no entry here falls back to English, matching the original behaviour.

export const DICT: Record<string, string> = {
  "Why NEXON": "لماذا نكسون",
  "Built in Dubai on a simple promise: honest migration advice.": "تأسسنا في دبي على وعدٍ بسيط: استشارات هجرة صادقة.",
  "NEXON Global Immigration Services exists because too many families receive vague timelines, hidden fees and programs they were never going to qualify for. We set out to do the opposite.": "وُجدت نكسون لخدمات الهجرة العالمية لأن عائلات كثيرة تتلقى جداول زمنية مبهمة، ورسومًا خفية، وبرامج لم تكن مؤهلة لها أصلًا. نحن قررنا أن نفعل العكس.",
  "Book a Consultation": "احجز استشارة",
  "How It Works": "كيف نعمل",
  "How it works": "كيف نعمل",
  "Our story": "قصتنا",
  "Who we serve": "من نخدم",
  "What we hold ourselves to": "ما نلتزم به",
  "Transparency first": "الشفافية أولًا",
  "Written fee schedules and engagement terms before you commit a dirham. No hidden charges, ever.": "جداول رسوم وشروط تعاقد مكتوبة قبل أن تدفع درهمًا واحدًا. لا رسوم خفية، أبدًا.",
  "Authorised programs only": "برامج معتمدة فقط",
  "We work exclusively with official, legally established residency and citizenship routes.": "نعمل حصريًا مع مسارات الإقامة والجنسية الرسمية والمعتمدة قانونيًا.",
  "Honesty over sales": "الصدق قبل البيع",
  "If your profile is not ready, we say so — and tell you exactly what would change the answer.": "إذا لم يكن ملفك جاهزًا نقول ذلك بوضوح، ونخبرك تحديدًا بما قد يغيّر الإجابة.",
  "One consultant, end to end": "مستشار واحد من البداية إلى النهاية",
  "A named advisor owns your file from first meeting to approval. You always know who to call.": "مستشار محدد بالاسم يتولى ملفك من أول اجتماع حتى الموافقة. تعرف دائمًا بمن تتصل.",
  "Years of combined advisory experience": "سنوات من الخبرة الاستشارية المجتمعة",
  "Residency & citizenship programs": "برامج الإقامة والجنسية",
  "residency & citizenship programs": "برنامجًا للإقامة والجنسية",
  "Languages spoken by our team": "لغات يتحدثها فريقنا",
  "1 day": "يوم واحد",
  "Maximum response time": "الحد الأقصى لوقت الرد",
  "Your advisors": "مستشاروك",
  "The people behind every application": "الأشخاص خلف كل طلب",
  "Talk to a consultant this week.": "تحدث مع مستشار هذا الأسبوع.",
  "Thirty minutes, free of charge, in English or Arabic. We reply to every enquiry within one business day.": "ثلاثون دقيقة، مجانًا، بالإنجليزية أو العربية. نرد على كل استفسار خلال يوم عمل واحد.",
  "Prefer WhatsApp?": "تفضّل واتساب؟",
  "Message us": "راسلنا",
  "and a consultant — not a bot — replies during office hours, usually within the hour.": "وسيرد عليك مستشار، وليس روبوتًا، خلال ساعات العمل، وعادةً في أقل من ساعة.",
  "Business Bay, Dubai, United Arab Emirates": "الخليج التجاري، دبي، الإمارات العربية المتحدة",
  "Sunday–Friday, 9:00–18:00 GST": "الأحد–الجمعة، 9:00–18:00 بتوقيت الخليج",
  "WhatsApp +971 50 000 0000": "واتساب +971 50 000 0000",
  "Full name": "الاسم الكامل",
  "Your full name": "اسمك الكامل",
  "Email": "البريد الإلكتروني",
  "Email address": "البريد الإلكتروني",
  "Phone / WhatsApp": "الهاتف / واتساب",
  "Phone / WhatsApp (optional)": "الهاتف / واتساب (اختياري)",
  "I'm interested in": "أنا مهتم بـ",
  "Select a practice": "اختر مجال الخدمة",
  "Citizenship by investment": "الجنسية عن طريق الاستثمار",
  "Residency by investment": "الإقامة عن طريق الاستثمار",
  "Skilled or family migration": "الهجرة المهنية أو العائلية",
  "Corporate / global mobility": "الشركات / التنقل العالمي",
  "Preferred meeting": "طريقة الاجتماع المفضلة",
  "Select an option": "اختر خيارًا",
  "Video call": "مكالمة فيديو",
  "Phone call": "مكالمة هاتفية",
  "In person — Dubai office": "حضوريًا — مكتب دبي",
  "Preferred language": "اللغة المفضلة",
  "Select a language": "اختر اللغة",
  "English": "الإنجليزية",
  "Message": "رسالتك",
  "Tell us briefly about your situation (optional)": "أخبرنا باختصار عن وضعك (اختياري)",
  "Book my free consultation": "احجز استشارتي المجانية",
  "Your details stay private and are never shared.": "بياناتك تبقى خاصة ولا نشاركها مع أي طرف.",
  "Request received.": "تم استلام طلبك.",
  "A consultant will contact you within one business day to schedule your consultation.": "سيتواصل معك مستشار خلال يوم عمل واحد لتحديد موعد استشارتك.",
  "Destinations & programs": "الوجهات والبرامج",
  "Where would you like to belong?": "أين تريد أن تنتمي؟",
  "Twelve government-authorised routes across citizenship, residency and skilled migration. Every figure below is the official minimum — we confirm current requirements before you commit.": "اثنا عشر مسارًا معتمدًا حكوميًا في الجنسية والإقامة والهجرة المهنية. كل رقم أدناه هو الحد الأدنى الرسمي، ونؤكد المتطلبات الحالية قبل أن تلتزم.",
  "Twelve government-authorised routes across citizenship, residency and skilled migration.": "اثنا عشر مسارًا معتمدًا حكوميًا في الجنسية والإقامة والهجرة المهنية.",
  "Program requirements change.": "متطلبات البرامج تتغير.",
  "Speak to an expert": "تحدث مع خبير",
  "Speak to an Expert": "تحدث مع خبير",
  "for figures verified this month.": "للحصول على أرقام مُحدّثة هذا الشهر.",
  "Eligibility check": "فحص الأهلية",
  "Find out where you stand in two minutes": "اعرف موقعك في دقيقتين",
  "Three quick questions. A consultant reviews every submission personally — no automated rejections.": "ثلاثة أسئلة سريعة. يراجع مستشار كل طلب شخصيًا، بلا رفض آلي.",
  "What is your primary goal?": "ما هدفك الأساسي؟",
  "What budget could you commit, if the route involves investment?": "ما الميزانية التي يمكنك الالتزام بها إذا كان المسار يتضمن استثمارًا؟",
  "Back": "رجوع",
  "Where should we send your assessment?": "إلى أين نرسل تقييمك؟",
  "Based on your answers:": "بناءً على إجاباتك:",
  "programs": "برامج",
  "look worth exploring.": "تستحق الاستكشاف.",
  "Get my assessment": "أرسلوا لي التقييم",
  "Thank you — assessment on its way.": "شكرًا لك، تقييمك في الطريق.",
  "A consultant will review your answers and reply within one business day with a shortlist and honest next steps.": "سيراجع مستشار إجاباتك ويرد خلال يوم عمل واحد بقائمة مختصرة وخطوات تالية صادقة.",
  "Start over": "ابدأ من جديد",
  "Second citizenship": "جنسية ثانية",
  "Residency abroad": "إقامة في الخارج",
  "Skilled migration (work visa)": "هجرة مهنية (تأشيرة عمل)",
  "Relocate my business": "نقل شركتي",
  "Under $100k": "أقل من 100 ألف دولار",
  "$100k – $250k": "100–250 ألف دولار",
  "$250k – $500k": "250–500 ألف دولار",
  "$500k+": "أكثر من 500 ألف دولار",
  "Not investment-based": "غير قائم على الاستثمار",
  "FAQs": "الأسئلة الشائعة",
  "Questions, answered plainly.": "أسئلة، بإجابات واضحة.",
  "If your question isn't here, a consultant will answer it on a free call — in English or Arabic.": "إذا لم تجد سؤالك هنا، سيجيب عنه مستشار في مكالمة مجانية، بالإنجليزية أو العربية.",
  "Questions, answered": "أسئلة وأجوبة",
  "Frequently asked": "الأسئلة الأكثر تكرارًا",
  "All FAQs": "كل الأسئلة الشائعة",
  "For business": "للشركات",
  "For Business": "للشركات",
  "Corporate & Global Mobility": "الشركات والتنقل العالمي",
  "Corporate & global mobility": "الشركات والتنقل العالمي",
  "Relocation of founders, executives and whole teams. Company setup, work permits and dependent visas handled end to end, with UAE free-zone expertise.": "انتقال المؤسسين والتنفيذيين والفرق بأكملها. تأسيس الشركات وتصاريح العمل وتأشيرات المرافقين من البداية إلى النهاية، بخبرة في المناطق الحرة الإماراتية.",
  "Our transparency promises": "وعودنا بالشفافية",
  "Our promises": "وعودنا",
  "Fees in writing, day one": "الرسوم مكتوبة من اليوم الأول",
  "Professional fees, government fees and third-party costs itemised before engagement. Nothing added later.": "الرسوم المهنية والحكومية وتكاليف الأطراف الثالثة مفصّلة قبل التعاقد. لا إضافات لاحقًا.",
  "No false timelines": "لا جداول زمنية زائفة",
  "We quote the timelines programs actually deliver, not the ones that close a sale.": "نقدّم المدد الزمنية التي تحققها البرامج فعلًا، لا تلك التي تُغلق صفقة.",
  "We decline weak cases": "نرفض الحالات الضعيفة",
  "If we believe an application will fail, we will not submit it — and we tell you what would change our answer.": "إذا رأينا أن الطلب سيُرفض فلن نقدّمه، ونخبرك بما قد يغيّر رأينا.",
  "What's included": "ما الذي تشمله الخدمة",
  "Typical clients: Startups, family offices, expanding SMEs": "العملاء المعتادون: شركات ناشئة، مكاتب عائلية، شركات صغيرة ومتوسطة في مرحلة التوسع",
  "Typical clients:": "العملاء المعتادون:",
  "Startups, family offices, expanding SMEs": "شركات ناشئة، مكاتب عائلية، شركات صغيرة ومتوسطة في مرحلة التوسع",
  "Services": "الخدمات",
  "Four practices. One clear path abroad.": "أربعة مجالات. مسار واحد واضح إلى الخارج.",
  "Citizenship by Investment": "الجنسية عن طريق الاستثمار",
  "Residency by Investment": "الإقامة عن طريق الاستثمار",
  "Skilled & Family Migration": "الهجرة المهنية والعائلية",
  "Skilled & family migration": "الهجرة المهنية والعائلية",
  "A clear process, from first call to approval.": "عملية واضحة، من أول مكالمة حتى الموافقة.",
  "Five stages. At each one you know exactly what we're doing, what it costs, and what you receive.": "خمس مراحل. في كل مرحلة تعرف تمامًا ما نقوم به، وكم يكلّف، وما الذي تحصل عليه.",
  "You receive:": "تحصل على:",
  "Insights": "رؤى ومقالات",
  "Latest from our desk": "آخر ما كتبه مستشارونا",
  "Latest": "الأحدث",
  "Guides": "أدلة",
  "All articles": "كل المقالات",
  "Migration, explained without the sales pitch.": "الهجرة، مشروحة بلا أسلوب البيع.",
  "Program changes, comparisons and practical guides from our consultants.": "تغييرات البرامج، ومقارنات، وأدلة عملية من مستشارينا.",
  "Featured · Europe": "مقال مميز · أوروبا",
  "Portugal's Golden Visa in 2026: what changed and who still qualifies": "التأشيرة الذهبية البرتغالية في 2026: ما الذي تغيّر ومن لا يزال مؤهلًا",
  "Portugal’s Golden Visa in 2026: what changed and who still qualifies": "التأشيرة الذهبية البرتغالية في 2026: ما الذي تغيّر ومن لا يزال مؤهلًا",
  "The fund route now dominates. Here is what the current rules mean for applicants weighing Portugal against Greece.": "مسار الصناديق يهيمن الآن. إليك ما تعنيه القواعد الحالية للمتقدمين الذين يقارنون بين البرتغال واليونان.",
  "By Layla Haddad · Aug 2026 · 6 min read": "بقلم ليلى حداد · أغسطس 2026 · 6 دقائق قراءة",
  "Comparing the five Caribbean citizenship programs, side by side": "مقارنة برامج الجنسية الكاريبية الخمسة جنبًا إلى جنب",
  "Donation levels, real-estate options, family costs and travel access — one table, no spin.": "مستويات التبرع، وخيارات العقارات، وتكاليف العائلة، وحرية السفر؛ في جدول واحد بلا تجميل.",
  "Every UAE Golden Visa category explained — investors to specialists": "شرح كل فئات التأشيرة الذهبية الإماراتية، من المستثمرين إلى المتخصصين",
  "Every UAE Golden Visa category explained": "شرح كل فئات التأشيرة الذهبية الإماراتية",
  "Investors, entrepreneurs, specialists, students: the thresholds and documents for each route.": "المستثمرون ورواد الأعمال والمتخصصون والطلاب: الحدود والمستندات لكل مسار.",
  "Express Entry vs provincial nomination: which gets you to Canada faster?": "Express Entry أم الترشيح الإقليمي: أيهما يوصلك إلى كندا أسرع؟",
  "Why a lower CRS score with the right province can beat a higher one without it.": "لماذا قد تتفوق درجة CRS أقل مع المقاطعة المناسبة على درجة أعلى من دونها.",
  "Due diligence: what citizenship units actually check": "العناية الواجبة: ما الذي تتحقق منه وحدات الجنسية فعلًا",
  "Source of funds, past refusals, name matches — and how to prepare a clean file.": "مصدر الأموال، والرفض السابق، وتطابق الأسماء؛ وكيف تجهّز ملفًا نظيفًا.",
  "Greece Golden Visa: the zones and thresholds in force now": "التأشيرة الذهبية اليونانية: المناطق والحدود المعمول بها الآن",
  "Where €250,000 still works, where it doesn’t, and what counts as one qualifying property.": "أين لا يزال مبلغ 250,000 يورو كافيًا، وأين لم يعد كذلك، وما الذي يُعدّ عقارًا مؤهلًا واحدًا.",
  "Adding parents and adult children to your application": "إضافة الوالدين والأبناء البالغين إلى طلبك",
  "Dependency rules differ sharply by program. Here’s who qualifies where.": "تختلف قواعد الإعالة اختلافًا كبيرًا بين البرامج. إليك من يستوفي الشروط وأين.",
  "Europe": "أوروبا",
  "Caribbean": "الكاريبي",
  "UAE": "الإمارات",
  "Family": "العائلة",
  "Aug 2026": "أغسطس 2026",
  "Jul 2026": "يوليو 2026",
  "Jun 2026": "يونيو 2026",
  "May 2026": "مايو 2026",
  "Free 30-minute consultation": "استشارة مجانية لمدة 30 دقيقة",
  "Free 30-minute consultation · No obligation · English & Arabic": "استشارة مجانية لمدة 30 دقيقة · بلا التزام · بالإنجليزية والعربية",
  "Your next country, handled with care and precision.": "بلدك القادم، بعناية ودقة.",
  "NEXON guides individuals, families, investors and skilled professionals through residency, citizenship and global mobility programs — from first consultation to approval, with full transparency at every step.": "ترشد نكسون الأفراد والعائلات والمستثمرين والمهنيين ذوي المهارات عبر برامج الإقامة والجنسية والتنقل العالمي، من أول استشارة حتى الموافقة، بشفافية كاملة في كل خطوة.",
  "Check Your Eligibility": "تحقق من أهليتك",
  "Every engagement begins with an honest assessment of your options — we only recommend programs you genuinely qualify for.": "يبدأ كل تعاقد بتقييم صادق لخياراتك، ولا نوصي إلا بالبرامج التي تكون مؤهلًا لها فعلًا.",
  "Every engagement begins with an honest assessment of your options. We only recommend programs you genuinely qualify for.": "يبدأ كل تعاقد بتقييم صادق لخياراتك. لا نوصي إلا بالبرامج التي تكون مؤهلًا لها فعلًا.",
  "Explore our services": "استكشف خدماتنا",
  "Second passports through government-authorised programs in the Caribbean, Türkiye and beyond — with full due-diligence support.": "جوازات سفر ثانية عبر برامج معتمدة حكوميًا في الكاريبي وتركيا وغيرها، مع دعم كامل للعناية الواجبة.",
  "Golden visas and investor residency across Europe and the UAE, matched to your budget, timeline and mobility goals.": "تأشيرات ذهبية وإقامات للمستثمرين في أوروبا والإمارات، بما يناسب ميزانيتك وجدولك الزمني وأهدافك في التنقل.",
  "Points-based pathways to Canada, Australia and the UK for professionals, plus family sponsorship and study routes.": "مسارات قائمة على النقاط إلى كندا وأستراليا والمملكة المتحدة للمهنيين، إضافة إلى كفالة العائلة ومسارات الدراسة.",
  "Relocation of founders, executives and teams — company setup, work permits and dependent visas handled end to end.": "انتقال المؤسسين والتنفيذيين والفرق: تأسيس الشركات وتصاريح العمل وتأشيرات المرافقين من البداية إلى النهاية.",
  "View all 12 destinations": "عرض جميع الوجهات الـ12",
  "Businesses": "الشركات",
  "For families": "للعائلات",
  "For professionals": "للمهنيين",
  "Families & individuals": "العائلات والأفراد",
  "Migration advice you can hold us to.": "استشارات هجرة يمكنك محاسبتنا عليها.",
  "Founded in Dubai by consultants with two decades of combined experience across investment migration and skilled visas, NEXON was built on a simple premise: clients deserve written fee schedules, realistic timelines, and only government-authorised programs.": "أسّس نكسون في دبي مستشارون بخبرة مجتمعة تمتد لعقدين في هجرة الاستثمار وتأشيرات المهارات، على مبدأ بسيط: يستحق العملاء جداول رسوم مكتوبة، ومددًا زمنية واقعية، وبرامج معتمدة حكوميًا فقط.",
  "Licensed and accountable": "مرخّصون ومسؤولون",
  "UAE-licensed consultancy with written fee schedules and engagement terms on every file.": "استشارية مرخّصة في الإمارات، بجداول رسوم وشروط تعاقد مكتوبة في كل ملف.",
  "Government-authorised programs only": "برامج معتمدة حكوميًا فقط",
  "Honest eligibility advice": "نصيحة أهلية صادقة",
  "If your profile is not ready, we say so — and tell you what would change the answer.": "إذا لم يكن ملفك جاهزًا نقول ذلك، ونخبرك بما قد يغيّر الإجابة.",
  "End-to-end, in your language": "من البداية إلى النهاية، بلغتك",
  "From due diligence to relocation, in English, Arabic and four more languages.": "من العناية الواجبة حتى الانتقال، بالإنجليزية والعربية وأربع لغات أخرى.",
  "A clear process, from day one": "عملية واضحة من اليوم الأول",
  "Families": "العائلات",
  "Individuals": "الأفراد",
  "Investors": "المستثمرون",
  "Entrepreneurs": "رواد الأعمال",
  "Skilled professionals": "المهنيون ذوو المهارات",
  "Education, healthcare and a secure future in one application.": "التعليم والرعاية الصحية ومستقبل آمن في طلب واحد.",
  "Relocating a business and team with minimal disruption.": "نقل شركة وفريق بأقل قدر من التعطيل.",
  "A second residency or passport as a plan B and travel freedom.": "إقامة أو جواز سفر ثانٍ كخطة بديلة وحرية في السفر.",
  "Programs that protect capital and open new markets.": "برامج تحمي رأس المال وتفتح أسواقًا جديدة.",
  "Points-based visas that turn experience into permanent residency.": "تأشيرات قائمة على النقاط تحوّل الخبرة إلى إقامة دائمة.",
  "UAE company formation — free zone and mainland": "تأسيس الشركات في الإمارات — المناطق الحرة والبر الرئيسي",
  "Executive and employee work permits": "تصاريح عمل التنفيذيين والموظفين",
  "Dependent and domestic-staff visas": "تأشيرات المرافقين والعمالة المنزلية",
  "Payroll and Emiratisation compliance guidance": "إرشادات الامتثال للرواتب والتوطين",
  "Ongoing PRO and renewals service": "خدمة مستمرة للمعاملات الحكومية والتجديدات",
  "Family inclusion strategy — spouse, children, parents": "استراتيجية ضمّ العائلة — الزوج/الزوجة والأبناء والوالدين",
  "Program comparison across all authorised CBI jurisdictions": "مقارنة البرامج عبر جميع دول الجنسية بالاستثمار المعتمدة",
  "Qualifying-investment selection and verification": "اختيار الاستثمار المؤهل والتحقق منه",
  "Residency-card processing and renewals": "إصدار بطاقات الإقامة وتجديدها",
  "Path-to-citizenship planning where available": "تخطيط مسار الجنسية حيث يتوفر",
  "Passport issuance and renewal support": "دعم إصدار جواز السفر وتجديده",
  "Points assessment and score-improvement plan": "تقييم النقاط وخطة تحسين الدرجة",
  "Express Entry, PNP, SkillSelect and UK Skilled Worker routes": "مسارات Express Entry وPNP وSkillSelect وتأشيرة العامل الماهر البريطانية",
  "Credential recognition and language-test guidance": "معادلة المؤهلات وإرشادات اختبارات اللغة",
  "Family sponsorship and dependent visas": "كفالة العائلة وتأشيرات المرافقين",
  "Job-search and settlement orientation": "توجيه للبحث عن عمل والاستقرار",
  "Pre-submission due-diligence screening": "فحص العناية الواجبة قبل التقديم",
  "Investment route guidance (donation, real estate, funds)": "إرشاد حول مسار الاستثمار (تبرع، عقارات، صناديق)",
  "Portugal, Greece, Cyprus, Malta, Latvia and UAE programs": "برامج البرتغال واليونان وقبرص ومالطا ولاتفيا والإمارات",
  "Tax-residency coordination with your advisors": "التنسيق بشأن الإقامة الضريبية مع مستشاريك",
  "A second passport through government-authorised programs in the Caribbean, Türkiye and beyond. We manage due diligence, investment structuring and the full application.": "جواز سفر ثانٍ عبر برامج معتمدة حكوميًا في الكاريبي وتركيا وغيرها. نتولى العناية الواجبة وهيكلة الاستثمار والطلب كاملًا.",
  "Investors, business families, frequent travellers": "المستثمرون، العائلات التجارية، كثيرو السفر",
  "Explore citizenship programs": "استكشف برامج الجنسية",
  "Golden visas and investor residency across Europe and the UAE, matched to your budget, timeline and long-term mobility goals — including paths to citizenship.": "تأشيرات ذهبية وإقامات للمستثمرين في أوروبا والإمارات، بما يناسب ميزانيتك وجدولك الزمني وأهدافك طويلة المدى في التنقل، بما في ذلك مسارات الجنسية.",
  "Investors, retirees, families seeking EU access": "المستثمرون، المتقاعدون، العائلات الساعية إلى الوصول للاتحاد الأوروبي",
  "View the Portugal Golden Visa": "اطّلع على التأشيرة الذهبية البرتغالية",
  "Points-based pathways to Canada, Australia and the UK for professionals — plus family sponsorship, study routes and post-study work options.": "مسارات قائمة على النقاط إلى كندا وأستراليا والمملكة المتحدة للمهنيين، إضافة إلى كفالة العائلة ومسارات الدراسة وخيارات العمل بعد الدراسة.",
  "Engineers, medics, tech and finance professionals": "المهندسون، الأطباء، مهنيو التقنية والمال",
  "Portugal Golden Visa": "التأشيرة الذهبية البرتغالية",
  "European residency with one week a year in-country, and one of the clearest paths to an EU passport.": "إقامة أوروبية بأسبوع واحد في السنة داخل البلاد، وأحد أوضح المسارات إلى جواز سفر أوروبي.",
  "Enquire about Portugal": "استفسر عن البرتغال",
  "Minimum investment": "الحد الأدنى للاستثمار",
  "Time to residency": "مدة الحصول على الإقامة",
  "6–8 months": "6–8 أشهر",
  "Stay requirement": "شرط الإقامة الفعلية",
  "7 days / year": "7 أيام / سنة",
  "Citizenship eligibility": "أهلية الجنسية",
  "After 5 years": "بعد 5 سنوات",
  "Qualifying investments": "الاستثمارات المؤهلة",
  "Routes and minimums per current Portuguese regulations; confirmed in writing at consultation.": "المسارات والحدود الدنيا وفق اللوائح البرتغالية الحالية؛ تُؤكَّد كتابيًا في الاستشارة.",
  "Minimum qualifying amount": "الحد الأدنى للمبلغ المؤهل",
  "Included in our service:": "تشمل خدمتنا:",
  "Who can apply": "من يمكنه التقديم",
  "A Portugal specialist replies within one business day with current requirements and a fee schedule.": "يرد مختص بالبرتغال خلال يوم عمل واحد بالمتطلبات الحالية وجدول الرسوم.",
  "Why Portugal": "لماذا البرتغال",
  "The Golden Visa grants residency to investors and their families with a physical-presence requirement of just seven days a year. After five years of legal residency, applicants may apply for permanent residency or citizenship — keeping their original nationality.": "تمنح التأشيرة الذهبية الإقامة للمستثمرين وعائلاتهم بشرط حضور فعلي لا يتجاوز سبعة أيام في السنة. وبعد خمس سنوات من الإقامة القانونية يمكن للمتقدمين طلب الإقامة الدائمة أو الجنسية، مع الاحتفاظ بجنسيتهم الأصلية.",
  "Live, work and study anywhere in Portugal; travel the Schengen Area visa-free": "العيش والعمل والدراسة في أي مكان في البرتغال؛ والسفر في منطقة شنغن بلا تأشيرة",
  "Include your spouse, dependent children and dependent parents in one application": "ضمّ الزوج/الزوجة والأبناء المعالين والوالدين المعالين في طلب واحد",
  "No requirement to relocate — keep your business and tax base where they are": "لا يلزم الانتقال؛ أبقِ عملك ومقرك الضريبي حيث هما",
  "Path to permanent residency or citizenship after five years": "مسار إلى الإقامة الدائمة أو الجنسية بعد خمس سنوات",
  "Access to Portuguese healthcare and education systems": "الاستفادة من نظامي الرعاية الصحية والتعليم في البرتغال",
  "Fund & research routes": "مسارات الصناديق والبحث",
  "Investment fund subscription · Research contribution": "الاشتراك في صندوق استثماري · المساهمة البحثية",
  "Investment fund subscription": "الاشتراك في صندوق استثماري",
  "CMVM-regulated venture or private-equity funds": "صناديق رأس مال مخاطر أو أسهم خاصة خاضعة لهيئة CMVM",
  "Research contribution": "المساهمة البحثية",
  "Accredited scientific or technological institutions": "مؤسسات علمية أو تقنية معتمدة",
  "Donation & business routes": "مسارات التبرع والأعمال",
  "Cultural & heritage donation · Company & job creation": "التبرع الثقافي والتراثي · تأسيس شركة وخلق وظائف",
  "Cultural & heritage donation": "التبرع الثقافي والتراثي",
  "Approved national heritage projects": "مشاريع تراث وطني معتمدة",
  "Company & job creation": "تأسيس شركة وخلق وظائف",
  "Portuguese company creating 10+ jobs": "شركة برتغالية تخلق 10 وظائف أو أكثر",
  "Varies": "يختلف",
  "Non-EU / EEA / Swiss nationals aged 18 or over": "مواطنو الدول من خارج الاتحاد الأوروبي / المنطقة الاقتصادية الأوروبية / سويسرا بعمر 18 عامًا أو أكثر",
  "Clean criminal record in Portugal and country of residence": "سجل جنائي خالٍ في البرتغال وبلد الإقامة",
  "Funds of lawful, documented origin": "أموال ذات مصدر مشروع وموثّق",
  "Ability to maintain the investment for at least five years": "القدرة على الاحتفاظ بالاستثمار لمدة خمس سنوات على الأقل",
  "© 2026 NEXON Global Immigration Services. All rights reserved.": "© 2026 نكسون لخدمات الهجرة العالمية. جميع الحقوق محفوظة.",
  "Privacy Policy": "سياسة الخصوصية",
  "Terms": "الشروط",
  "Contact": "اتصل بنا",
  "Residency, citizenship and global mobility consultancy. Licensed in the United Arab Emirates.": "استشارات الإقامة والجنسية والتنقل العالمي. مرخّصة في الإمارات العربية المتحدة.",
  "English · العربية coming soon": "العربية · English",
  "Residency & skilled": "الإقامة والهجرة المهنية",
  "Resources": "الموارد",
  "Success Stories": "قصص النجاح",
  "Success stories": "قصص النجاح",
  "Destinations": "الوجهات",
  "Company": "الشركة",
  "About Us": "من نحن",
  "About us": "من نحن",
  "Families who made the move.": "عائلات اتخذت خطوة الانتقال.",
  "Names abbreviated for privacy. Programs, timelines and outcomes as delivered.": "الأسماء مختصرة حفاظًا على الخصوصية. البرامج والمدد والنتائج كما تحققت.",
  "Case study ·": "دراسة حالة ·",
  "What clients say": "ماذا يقول عملاؤنا",
  "4.9 average · verified reviews": "متوسط 4.9 · تقييمات موثّقة",
  "Investment migration": "هجرة الاستثمار",
  "Skilled migration": "الهجرة المهنية",
  "A family of five secures Grenada citizenship in seven months": "عائلة من خمسة أفراد تحصل على جنسية غرينادا في سبعة أشهر",
  "A Dubai-based business family wanted visa-free access to 140+ destinations and a plan B for their children. After due diligence flagged a documentation gap, we resolved it pre-submission — the application passed government vetting on the first pass.": "أرادت عائلة تجارية مقيمة في دبي الوصول بلا تأشيرة إلى أكثر من 140 وجهة وخطة بديلة لأبنائها. وبعد أن كشفت العناية الواجبة فجوة في المستندات، عالجناها قبل التقديم، فاجتاز الطلب التدقيق الحكومي من المرة الأولى.",
  "7 mo": "7 أشهر",
  "first call to passports": "من أول مكالمة إلى جوازات السفر",
  "family members, one file": "أفراد عائلة، ملف واحد",
  "government queries": "استفسارات حكومية",
  "A software engineer lands Canadian PR through a provincial route": "مهندس برمجيات يحصل على الإقامة الدائمة الكندية عبر مسار إقليمي",
  "After a year of researching Express Entry alone, his CRS score fell short. Our points plan — a language retake and a provincial nomination stream matched to his stack — added 620 points and produced an invitation to apply in four months.": "بعد عام من البحث في Express Entry بمفرده، لم تكفِ درجته في CRS. أضافت خطة النقاط لدينا — إعادة اختبار اللغة ومسار ترشيح إقليمي يناسب تخصصه — 620 نقطة، وأثمرت دعوة للتقديم في أربعة أشهر.",
  "4 mo": "4 أشهر",
  "to invitation": "حتى الدعوة",
  "CRS with nomination": "درجة CRS مع الترشيح",
  "11 mo": "11 شهرًا",
  "to PR confirmation": "حتى تأكيد الإقامة الدائمة",
  "They told us in the first meeting which program we did not qualify for, and why. That honesty is exactly why we trusted them with the one we did.": "أخبرونا في أول اجتماع أي برنامج لا نستوفي شروطه، ولماذا. هذا الصدق تحديدًا هو ما جعلنا نثق بهم في البرنامج الذي استوفينا شروطه.",
  "S. Rahman & family": "س. رحمن وعائلته",
  "Grenada Citizenship by Investment": "الجنسية بالاستثمار في غرينادا",
  "From document collection to the golden visa stamp, everything ran on the timeline they wrote down on day one. Not a single surprise fee.": "من جمع المستندات حتى ختم التأشيرة الذهبية، سار كل شيء وفق الجدول الزمني الذي كتبوه في اليوم الأول. ولا رسم مفاجئ واحد.",
  "K. Osei": "ك. أوسي",
  "UAE Golden Visa · Investor category": "التأشيرة الذهبية الإماراتية · فئة المستثمر",
  "NEXON found the provincial route I had missed and my invitation came in four months.": "وجدت نكسون المسار الإقليمي الذي فاتني، وجاءتني الدعوة في أربعة أشهر.",
  "As a software engineer I had researched Express Entry for a year. NEXON found the provincial route I had missed and my ITA came in four months.": "كمهندس برمجيات، بحثت في Express Entry لمدة عام. وجدت نكسون المسار الإقليمي الذي فاتني، وجاءتني دعوة التقديم في أربعة أشهر.",
  "D. Petrov": "د. بيتروف",
  "Canada Express Entry · PNP": "كندا Express Entry · ترشيح إقليمي",
  "We compared three agencies. NEXON was the only one that put every cost in writing before asking for a commitment.": "قارنّا بين ثلاث وكالات. كانت نكسون الوحيدة التي كتبت كل تكلفة قبل أن تطلب أي التزام.",
  "A. Al Mansoori": "أ. المنصوري",
  "The fortnightly updates meant we never once had to chase. Our consultant answered on WhatsApp even during Eid.": "التحديثات كل أسبوعين جعلتنا لا نحتاج إلى المتابعة ولا مرة. وكان مستشارنا يجيب على واتساب حتى في أيام العيد.",
  "M. & J. Fernandes": "م. وج. فرنانديز",
  "Greece Golden Visa": "التأشيرة الذهبية اليونانية",
  "They handled my company setup, my visa and my family’s visas as one project. One point of contact for everything.": "تولّوا تأسيس شركتي وتأشيرتي وتأشيرات عائلتي كمشروع واحد. جهة اتصال واحدة لكل شيء.",
  "T. Nakamura": "ت. ناكامورا",
  "Corporate relocation · DMCC free zone": "انتقال شركة · منطقة DMCC الحرة",
  "Part 1 of 3": "الجزء 1 من 3",
  "Part 2 of 3": "الجزء 2 من 3",
  "Part 3 of 3": "الجزء 3 من 3",
  "NEXON was founded by consultants who spent a combined twenty years inside investment-migration firms and skilled-visa practices across the Gulf. We saw what worked — and what clients were never told.": "أسّس نكسون مستشارون قضوا ما مجموعه عشرين عامًا داخل شركات هجرة الاستثمار ومكاتب تأشيرات المهارات في الخليج. رأينا ما ينجح، وما لم يُخبَر به العملاء يومًا.",
  "So we built a consultancy around written fee schedules, realistic timelines, and government-authorised programs only. Every file is handled by a named consultant you can call, in English or Arabic, from first meeting to final approval.": "فبنينا استشارية تقوم على جداول رسوم مكتوبة، ومدد زمنية واقعية، وبرامج معتمدة حكوميًا فقط. يتولى كل ملف مستشار محدد بالاسم يمكنك الاتصال به، بالإنجليزية أو العربية، من أول اجتماع حتى الموافقة النهائية.",
  "Today we advise individuals, families, investors, entrepreneurs and skilled professionals across 35+ residency and citizenship programs worldwide.": "اليوم نقدّم المشورة للأفراد والعائلات والمستثمرين ورواد الأعمال والمهنيين ذوي المهارات عبر أكثر من 35 برنامجًا للإقامة والجنسية حول العالم.",
  "Layla Haddad": "ليلى حداد",
  "Managing Partner": "الشريكة الإدارية",
  "12 years in investment migration · Member, Investment Migration Council · Arabic, English, French": "12 عامًا في هجرة الاستثمار · عضو مجلس هجرة الاستثمار · العربية والإنجليزية والفرنسية",
  "Omar Al Farsi": "عمر الفارسي",
  "Head of Investment Migration": "رئيس قسم هجرة الاستثمار",
  "Former program liaison for two Caribbean CBI units · 300+ files advised · Arabic, English": "منسق سابق لبرنامجَين لدى وحدتَين كاريبيتَين للجنسية بالاستثمار · أكثر من 300 ملف · العربية والإنجليزية",
  "Priya Nair": "بريا نائير",
  "Senior Consultant, Skilled Migration": "مستشارة أولى، الهجرة المهنية",
  "Regulated migration adviser (Canada & Australia routes) · 9 years experience · English, Hindi, Malayalam": "مستشارة هجرة مرخّصة (مسارات كندا وأستراليا) · 9 سنوات خبرة · الإنجليزية والهندية والمالايالامية",
  "All": "الكل",
  "Residency": "الإقامة",
  "Citizenship": "الجنسية",
  "Skilled": "الهجرة المهنية",
  "Portugal": "البرتغال",
  "Greece": "اليونان",
  "Cyprus": "قبرص",
  "Malta": "مالطا",
  "UAE Golden Visa": "التأشيرة الذهبية الإماراتية",
  "United States": "الولايات المتحدة",
  "Grenada": "غرينادا",
  "St Kitts & Nevis": "سانت كيتس ونيفيس",
  "Antigua & Barbuda": "أنتيغوا وبربودا",
  "Türkiye": "تركيا",
  "Canada": "كندا",
  "Australia": "أستراليا",
  "From €250,000": "من 250,000 يورو",
  "From €300,000": "من 300,000 يورو",
  "From €150,000": "من 150,000 يورو",
  "From AED 2,000,000": "من 2,000,000 درهم",
  "EB-5 · from $800,000": "EB-5 · من 800,000 دولار",
  "From $235,000": "من 235,000 دولار",
  "From $250,000": "من 250,000 دولار",
  "From $230,000": "من 230,000 دولار",
  "From $400,000": "من 400,000 دولار",
  "Express Entry · points-based": "Express Entry · نظام النقاط",
  "SkillSelect · points-based": "SkillSelect · نظام النقاط",
  "6–8 months · 7 days/yr stay · citizenship after 5 yrs": "6–8 أشهر · إقامة 7 أيام/سنة · الجنسية بعد 5 سنوات",
  "6–8 months · 7 days/yr stay": "6–8 أشهر · إقامة 7 أيام/سنة",
  "3–4 months · no stay requirement": "3–4 أشهر · بلا شرط إقامة",
  "3–4 months · permanent residency": "3–4 أشهر · إقامة دائمة",
  "6–8 months · EU permanent residence": "6–8 أشهر · إقامة دائمة في الاتحاد الأوروبي",
  "2–4 weeks · 10-year renewable visa": "2–4 أسابيع · تأشيرة 10 سنوات قابلة للتجديد",
  "24–36 months · green card for the family": "24–36 شهرًا · البطاقة الخضراء للعائلة",
  "6–9 months · E-2 treaty with the US": "6–9 أشهر · معاهدة E-2 مع الولايات المتحدة",
  "4–6 months · longest-running CBI program": "4–6 أشهر · أقدم برنامج للجنسية بالاستثمار",
  "6–9 months · best value for larger families": "6–9 أشهر · الخيار الأنسب للعائلات الكبيرة",
  "3–4 months · real-estate route": "3–4 أشهر · مسار عقاري",
  "6–12 months · PR for the whole family": "6–12 شهرًا · إقامة دائمة للعائلة بأكملها",
  "8–14 months · skilled independent & state routes": "8–14 شهرًا · مسارات المهارات المستقلة ومسارات الولايات",
  "View program": "عرض البرنامج",
  "Enquire": "استفسر",
  "Get assessed": "احصل على تقييم",
  "Getting started": "البداية",
  "How do I know which program is right for me?": "كيف أعرف البرنامج المناسب لي؟",
  "Start with the free consultation or the two-minute eligibility check. We compare your nationality, budget, family situation and goals against 35+ programs and give you a written shortlist with reasons.": "ابدأ بالاستشارة المجانية أو فحص الأهلية الذي يستغرق دقيقتين. نقارن جنسيتك وميزانيتك ووضعك العائلي وأهدافك مع أكثر من 35 برنامجًا، ونقدّم لك قائمة مختصرة مكتوبة مع الأسباب.",
  "How long does the process take?": "كم يستغرق الإجراء؟",
  "UAE Golden Visas can complete in weeks; Caribbean citizenship typically takes 4–9 months; European residency 3–8 months; skilled migration to Canada or Australia 6–14 months. You receive a written timeline before you commit.": "قد تُستكمل التأشيرة الذهبية الإماراتية في أسابيع؛ وتستغرق الجنسية الكاريبية عادةً 4–9 أشهر؛ والإقامة الأوروبية 3–8 أشهر؛ والهجرة المهنية إلى كندا أو أستراليا 6–14 شهرًا. تحصل على جدول زمني مكتوب قبل أن تلتزم.",
  "It depends on the program. UAE Golden Visas can complete in weeks; Caribbean citizenship typically takes 4–9 months; European residency 3–8 months; skilled migration to Canada or Australia 6–14 months. We give you a written timeline before you commit.": "يعتمد ذلك على البرنامج. قد تُستكمل التأشيرة الذهبية الإماراتية في أسابيع؛ وتستغرق الجنسية الكاريبية عادةً 4–9 أشهر؛ والإقامة الأوروبية 3–8 أشهر؛ والهجرة المهنية إلى كندا أو أستراليا 6–14 شهرًا. نقدّم لك جدولًا زمنيًا مكتوبًا قبل أن تلتزم.",
  "Do I need to visit your office in Dubai?": "هل يلزم أن أزور مكتبكم في دبي؟",
  "No. Most clients complete the entire process remotely via video calls and courier. You are welcome at our Business Bay office at any stage.": "لا. يُنجز معظم العملاء الإجراء كاملًا عن بُعد عبر مكالمات الفيديو والبريد السريع. ونرحّب بك في مكتبنا في الخليج التجاري في أي مرحلة.",
  "Costs & fees": "التكاليف والرسوم",
  "Are your fees fixed and transparent?": "هل رسومكم ثابتة وشفافة؟",
  "Yes. You receive a written fee schedule at the first consultation covering our professional fees, government fees and third-party costs. Nothing is added later.": "نعم. تحصل في الاستشارة الأولى على جدول رسوم مكتوب يغطي رسومنا المهنية والرسوم الحكومية وتكاليف الأطراف الثالثة. لا يُضاف شيء لاحقًا.",
  "Yes. You receive a written fee schedule at the first consultation covering our professional fees, government fees, and third-party costs. No hidden charges are added later.": "نعم. تحصل في الاستشارة الأولى على جدول رسوم مكتوب يغطي رسومنا المهنية والرسوم الحكومية وتكاليف الأطراف الثالثة. لا تُضاف أي رسوم خفية لاحقًا.",
  "When do I pay?": "متى أدفع؟",
  "Fees are staged against milestones — engagement, submission and approval. You never pay the full amount upfront.": "تُقسَّم الرسوم على مراحل: التعاقد، والتقديم، والموافقة. لا تدفع المبلغ كاملًا مقدمًا أبدًا.",
  "What happens to my money if the application is refused?": "ماذا يحدث لأموالي إذا رُفض الطلب؟",
  "We only submit applications we believe will succeed, and our agreements set out clearly what is refundable at each stage. Most program investments are only committed after government pre-approval where the program allows.": "لا نقدّم إلا الطلبات التي نعتقد أنها ستنجح، وتوضّح اتفاقياتنا بدقة ما يُستردّ في كل مرحلة. ولا تُلتزم معظم استثمارات البرامج إلا بعد الموافقة الحكومية المبدئية حيث يسمح البرنامج بذلك.",
  "Family & eligibility": "العائلة والأهلية",
  "Can my family be included in one application?": "هل يمكن ضمّ عائلتي في طلب واحد؟",
  "Most programs allow spouses, dependent children and often parents in a single application. We confirm exactly who qualifies during your eligibility assessment.": "تسمح معظم البرامج بضمّ الزوج/الزوجة والأبناء المعالين وغالبًا الوالدين في طلب واحد. ونؤكد تحديدًا من يستوفي الشروط خلال تقييم الأهلية.",
  "Most programs allow spouses, dependent children, and in many cases parents to be included in a single application. We confirm exactly who qualifies during your eligibility assessment.": "تسمح معظم البرامج بضمّ الزوج/الزوجة والأبناء المعالين، وفي حالات كثيرة الوالدين، في طلب واحد. ونؤكد تحديدًا من يستوفي الشروط خلال تقييم الأهلية.",
  "Will a past visa refusal hurt my application?": "هل يضرّ رفض تأشيرة سابق بطلبي؟",
  "Not necessarily, but it must be disclosed and addressed properly. Our due-diligence stage exists precisely to surface and resolve issues before submission.": "ليس بالضرورة، لكن يجب الإفصاح عنه ومعالجته بشكل صحيح. مرحلة العناية الواجبة لدينا موجودة تحديدًا لكشف المشكلات وحلّها قبل التقديم.",
  "Do I need to speak the destination country’s language?": "هل يلزم أن أتحدث لغة بلد الوجهة؟",
  "Investment programs generally have no language requirement. Skilled routes to Canada, Australia and the UK do — we include language-test strategy in your points plan.": "لا تشترط برامج الاستثمار عمومًا أي لغة. أما المسارات المهنية إلى كندا وأستراليا والمملكة المتحدة فتشترطها، ونُدرج استراتيجية اختبار اللغة في خطة النقاط الخاصة بك.",
  "After approval": "بعد الموافقة",
  "Do I need to live in the country to keep my status?": "هل يلزم أن أعيش في البلد للاحتفاظ بوضعي؟",
  "Many investment programs have minimal or no physical-presence requirements — Portugal asks for about seven days a year; Greece has none. Skilled visas usually require genuine residence. Every obligation is flagged before you apply.": "كثير من برامج الاستثمار لا تشترط الحضور الفعلي أو تشترطه بحدّه الأدنى؛ تطلب البرتغال نحو سبعة أيام في السنة، ولا تشترط اليونان شيئًا. أما تأشيرات المهارات فتتطلب عادةً إقامة حقيقية. نوضّح كل التزام قبل أن تتقدم.",
  "Many investment programs have minimal or no physical residency requirements. Skilled visas usually do. We flag every residency obligation clearly before you apply.": "كثير من برامج الاستثمار لا تشترط الإقامة الفعلية أو تشترطها بحدّها الأدنى. أما تأشيرات المهارات فتشترطها عادةً. نوضّح كل التزام إقامة بجلاء قبل أن تتقدم.",
  "Can I lose my second citizenship or residency?": "هل يمكن أن أفقد جنسيتي أو إقامتي الثانية؟",
  "Citizenship, once granted, is rarely revoked except for fraud in the application. Residency permits must be renewed and their conditions maintained — we manage renewal calendars for all clients.": "نادرًا ما تُسحب الجنسية بعد منحها إلا في حالات الاحتيال في الطلب. أما تصاريح الإقامة فيجب تجديدها والحفاظ على شروطها، ونحن ندير جداول التجديد لجميع عملائنا.",
  "Do you help after the visa is issued?": "هل تساعدون بعد إصدار التأشيرة؟",
  "Yes. Settlement support — bank accounts, schools, property, renewals — is part of the engagement, not an upsell.": "نعم. دعم الاستقرار — الحسابات البنكية والمدارس والعقارات والتجديدات — جزء من التعاقد، وليس خدمة إضافية مدفوعة.",
  "What if my application is refused?": "ماذا لو رُفض طلبي؟",
  "We only submit applications we believe will succeed, and we tell you upfront if your profile is not ready. Where programs allow, our agreements set out clearly what is refundable at each stage.": "لا نقدّم إلا الطلبات التي نعتقد أنها ستنجح، ونخبرك مقدمًا إذا لم يكن ملفك جاهزًا. وحيث تسمح البرامج، توضّح اتفاقياتنا بدقة ما يُستردّ في كل مرحلة.",
  "Free consultation": "استشارة مجانية",
  "30 minutes": "30 دقيقة",
  "A call or office visit to understand your goals, family situation, nationality and constraints. We tell you plainly which routes are realistic.": "مكالمة أو زيارة للمكتب لفهم أهدافك ووضعك العائلي وجنسيتك وقيودك. نخبرك بوضوح أي المسارات واقعية.",
  "A shortlist of viable programs and a written fee schedule — before you pay anything.": "قائمة مختصرة بالبرامج الممكنة وجدول رسوم مكتوب، قبل أن تدفع أي شيء.",
  "Eligibility & due diligence": "الأهلية والعناية الواجبة",
  "1–2 weeks": "1–2 أسبوع",
  "We assess your profile against program requirements, run preliminary background checks, and flag any issues that could affect approval — before submission, not after.": "نقيّم ملفك مقابل متطلبات البرنامج، ونجري فحوصات خلفية مبدئية، ونحدّد أي مشكلات قد تؤثر في الموافقة، قبل التقديم لا بعده.",
  "A written eligibility report with risks, remedies and realistic approval odds.": "تقرير أهلية مكتوب يتضمن المخاطر والحلول واحتمالات الموافقة الواقعية.",
  "Program selection": "اختيار البرنامج",
  "1 week": "أسبوع واحد",
  "A side-by-side comparison of your best options: total costs, timelines, residency obligations, family inclusion and paths to citizenship.": "مقارنة جنبًا إلى جنب لأفضل خياراتك: التكاليف الإجمالية، والمدد الزمنية، والتزامات الإقامة، وضمّ العائلة، ومسارات الجنسية.",
  "A comparison document and a recommended route, with reasons in writing.": "وثيقة مقارنة ومسار موصى به، مع الأسباب مكتوبة.",
  "Application & documentation": "الطلب والمستندات",
  "varies by program": "يختلف حسب البرنامج",
  "We prepare, translate, attest and submit your file, and manage every government query. You get a named consultant and status updates at least fortnightly.": "نجهّز ملفك ونترجمه ونصدّقه ونقدّمه، ونتولى كل استفسار حكومي. يكون لك مستشار محدد بالاسم وتحديثات للحالة كل أسبوعين على الأقل.",
  "A tracked application with a live document checklist and update schedule.": "طلب مُتابَع مع قائمة مستندات محدّثة وجدول للتحديثات.",
  "Approval & beyond": "الموافقة وما بعدها",
  "ongoing": "مستمر",
  "Biometrics, oaths, property closings, bank accounts, school searches — we stay engaged until you and your family are actually settled, and handle renewals after.": "البصمات، وأداء القسم، وإتمام صفقات العقارات، والحسابات البنكية، والبحث عن مدارس؛ نبقى معك حتى تستقر أنت وعائلتك فعلًا، ثم نتولى التجديدات بعد ذلك.",
  "Your residency card or passport in hand, plus a settlement checklist and renewal calendar.": "بطاقة إقامتك أو جواز سفرك في يدك، مع قائمة استقرار وجدول تجديد.",
  "A 30-minute call to understand your goals, family situation and constraints.": "مكالمة لمدة 30 دقيقة لفهم أهدافك ووضعك العائلي وقيودك.",
  "We assess your profile against program requirements and run preliminary checks.": "نقيّم ملفك مقابل متطلبات البرنامج ونجري فحوصات مبدئية.",
  "A written comparison of your best options — costs, timelines and obligations.": "مقارنة مكتوبة لأفضل خياراتك: التكاليف والمدد الزمنية والالتزامات.",
  "We prepare, review and submit your file, and manage every government query.": "نجهّز ملفك ونراجعه ونقدّمه، ونتولى كل استفسار حكومي.",
  "Biometrics, oaths, property closings and relocation support until you are settled.": "البصمات وأداء القسم وإتمام صفقات العقارات ودعم الانتقال حتى تستقر.",
  "Meet us before you decide anything.": "قابلنا قبل أن تقرر أي شيء.",
  "Can't decide between two programs?": "محتار بين برنامجَين؟",
  "We'll prepare a written side-by-side comparison for your exact situation — free.": "سنُعدّ لك مقارنة مكتوبة جنبًا إلى جنب لوضعك بالتحديد، مجانًا.",
  "Still have a question?": "لا يزال لديك سؤال؟",
  "Not sure which practice fits your case?": "لست متأكدًا أي مجال يناسب حالتك؟",
  "Start with stage one — it's free.": "ابدأ بالمرحلة الأولى، فهي مجانية.",
  "Prefer answers specific to your case?": "تفضّل إجابات تخص حالتك؟",
  "Ready to take the first step?": "مستعد لاتخاذ الخطوة الأولى؟",
  "Your story could be next.": "قد تكون قصتك التالية.",
  "Previous": "السابق",
  "Next": "التالي",
  "Dismiss": "إغلاق",
  "Search": "بحث",
  "Language": "اللغة",
  "Menu": "القائمة",
  "Close menu": "إغلاق القائمة"
};
